### ISSUE TITLE
.docx file used 

### ISSUE THREAD

**Issue by fireproofsocks** [tomgros/group-projects#1]
Unless you have a very specific need for using a Microsoft Word .docx file, then it's best to keep your repository files simple so you are not putting unnecessary requirements on those who wish to look at your repo. A text or markdown file would be a better option in this case since there is nothing inside this document that requires the features available only to Microsoft Word.

**Comment by Milagu** [comment]
Deleted all .dox files from the repo.  Thank you.

**Comment by Milagu** [comment]
Fixed.
